apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcache-deploy
spec:
  selector:
    matchLabels:
      app: memcache
  template:
    metadata:
      labels:
        app: memcache
    spec:
      containers:
        - name: vprocache02
          image: memcached
          ports:
            - name: mem-port
              containerPort: 11211
               
